from __future__ import annotations

import io
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo

from backend.models.schemas import ColumnSchema
from backend.utils.helpers import guess_column_type, utc_now_iso


DARK_FILL = PatternFill("solid", fgColor="0D0F14")
HEADER_FILL = PatternFill("solid", fgColor="0D0F14")
EVEN_FILL = PatternFill("solid", fgColor="FFFFFF")
ODD_FILL = PatternFill("solid", fgColor="F2F5F7")
FOOTER_FONT = Font(color="808080", italic=True)
HEADER_FONT = Font(color="FFFFFF", bold=True)


def _column_format(column_type: str) -> str | None:
    if column_type == "currency":
        return '$#,##0.00'
    if column_type == "date":
        return 'DD-MMM-YYYY'
    if column_type == "number":
        return '0.00'
    if column_type == "percentage":
        return '0.00%'
    return None


def _safe_string(value: Any) -> str:
    return "" if value is None else str(value)


def create_excel_workbook(columns: list[ColumnSchema], rows: list[list[Any]], filename: str | None = None) -> tuple[bytes, str]:
    wb = Workbook()
    ws = wb.active
    ws.title = "ExcelAI Data"
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = None

    headers = [column.name for column in columns]
    ws.append(headers)

    column_types = [column.type or "text" for column in columns]
    for row in rows:
        ws.append(row)

    if rows:
        footer_row = len(rows) + 2
    else:
        footer_row = 2

    for cell in ws[1]:
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for row_index, row in enumerate(ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=len(headers)), start=2):
        fill = EVEN_FILL if row_index % 2 == 0 else ODD_FILL
        for col_index, cell in enumerate(row):
            cell.fill = fill
            cell.alignment = Alignment(vertical="top")
            if col_index < len(column_types):
                cell.number_format = _column_format(column_types[col_index]) or cell.number_format
                if column_types[col_index] in {"number", "currency", "percentage"}:
                    cell.alignment = Alignment(horizontal="right", vertical="top")

    if headers:
        end_col = ws.cell(row=1, column=len(headers)).column_letter
        table_ref = f"A1:{end_col}{max(1, len(rows) + 1)}"
        table = Table(displayName="ExcelAIData", ref=table_ref)
        table.tableStyleInfo = TableStyleInfo(
            name="TableStyleMedium2",
            showFirstColumn=False,
            showLastColumn=False,
            showRowStripes=False,
            showColumnStripes=False,
        )
        ws.add_table(table)
        ws.auto_filter.ref = table_ref

    widths: dict[int, int] = {}
    for row in ws.iter_rows():
        for cell in row:
            value_length = len(_safe_string(cell.value))
            widths[cell.column] = max(widths.get(cell.column, 0), min(value_length, 40))
    for index, width in widths.items():
        ws.column_dimensions[ws.cell(row=1, column=index).column_letter].width = max(width + 2, 12)

    footer_cell = ws.cell(row=footer_row, column=1)
    footer_cell.value = f"Generated by ExcelAI — {utc_now_iso()}"
    footer_cell.font = FOOTER_FONT
    footer_cell.fill = PatternFill("solid", fgColor="FFFFFF")

    buffer = io.BytesIO()
    wb.save(buffer)
    output_name = filename or "ExcelAI_Export.xlsx"
    if not output_name.lower().endswith(".xlsx"):
        output_name += ".xlsx"
    return buffer.getvalue(), output_name


def infer_column_schemas_from_rows(rows: list[list[Any]], headers: list[str] | None = None) -> list[ColumnSchema]:
    if not rows:
        return [ColumnSchema(name="Content", type="text")]
    column_count = max(len(row) for row in rows)
    headers = headers or [f"Column {index + 1}" for index in range(column_count)]
    columns: list[ColumnSchema] = []
    for index in range(column_count):
        values = [row[index] for row in rows if index < len(row)]
        columns.append(ColumnSchema(name=headers[index] if index < len(headers) else f"Column {index + 1}", type=guess_column_type(values)))
    return columns
